version: 2.1

description: Run PHPUnit tests

display:
    home_url: "https://stockfiller.com"
    source_url: "https://github.com/stockfiller/phpunit-orb"

orbs:
    composer: stockfiller/composer@0.0.30

executors:
    default:
        docker:
            -   image: cimg/php:7.4
        resource_class: small

jobs:
    test:
        parameters:
            executor:
                type: executor
                default: default
                description: Environment to run the tests inside
            path:
                type: string
                default: vendor/bin/phpunit
                description: Path to the PHPUnit executable inside the environment. Defaults to locally installed PHPUnit inside repository.
            flags:
                type: string
                description: Optional PHPUnit flags to append to the test command
                default: ""
        executor: << parameters.executor >>
        environment:
            TEST_RESULTS_PATH: test-results
        steps:
            - checkout
            - composer/install_dependencies
            -   run:
                    name: Run PHPUnit tests
                    command: << parameters.path >> --log-junit ${TEST_RESULTS_PATH}/tests.xml --do-not-cache-result << parameters.flags >>
            -   store_test_results:
                    path: "${TEST_RESULTS_PATH}"
            -   store_artifacts:
                    path: "${TEST_RESULTS_PATH}"
